[server]
fileWatcherType = "auto"
runOnSave = true

[browser]
gatherUsageStats = false

[theme]
primaryColor="#4361ee"
backgroundColor="#f8f9fa"
secondaryBackgroundColor="#e9ecef"
textColor="#212529"
font="sans serif"
